apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adla-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - adla.gov.gh
      secretName: adla-production-tls
  rules:
    - host: adla.gov.gh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adla-app
                port:
                  number: 3000
