apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adla-ingress
  labels:
    app.kubernetes.io/part-of: adla
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging-alda.audit.gov.gh
      secretName: adla-tls
  rules:
    - host: staging-alda.audit.gov.gh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adla-app
                port:
                  number: 3000
