apiVersion: v1
kind: ResourceQuota
metadata:
  name: adla-quota
  labels:
    app.kubernetes.io/part-of: adla
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "5"
