apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adla-staging

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: hpa-patch.yaml

images:
  - name: regisry.azurecr.io/adla-app
    newTag: staging-latest
  - name: regisry.azurecr.io/adla-migrate
    newTag: staging-latest
